// <auto-generated />
using System;
using InvServer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvServer.Infrastructure.Migrations
{
    [DbContext(typeof(InvDbContext))]
    partial class InvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("InvServer.Core.Entities.AccessScopeType", b =>
                {
                    b.Property<long>("AccessScopeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AccessScopeTypeId");

                    b.ToTable("ACCESS_SCOPE_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTable")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG");
                });

            modelBuilder.Entity("InvServer.Core.Entities.AuthSession", b =>
                {
                    b.Property<long>("AuthSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthSessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AUTH_SESSION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("CATEGORY");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("DEPARTMENT");
                });

            modelBuilder.Entity("InvServer.Core.Entities.IdempotencyKey", b =>
                {
                    b.Property<long>("IdempotencyKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MovementId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdempotencyKeyId");

                    b.HasIndex("UserId", "RouteKey", "Key")
                        .IsUnique();

                    b.ToTable("IDEMPOTENCY_KEY");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryMovementStatus", b =>
                {
                    b.Property<long>("MovementStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovementStatusId");

                    b.ToTable("INVENTORY_MOVEMENT_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryMovementType", b =>
                {
                    b.Property<long>("MovementTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovementTypeId");

                    b.ToTable("INVENTORY_MOVEMENT_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryReasonCode", b =>
                {
                    b.Property<long>("ReasonCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReasonCodeId");

                    b.ToTable("INVENTORY_REASON_CODE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequestTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WorkflowInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestNo")
                        .IsUnique();

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("INVENTORY_REQUEST");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequestLine", b =>
                {
                    b.Property<long>("RequestLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineNotes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("QtyApproved")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QtyFulfilled")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QtyRequested")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.ToTable("INVENTORY_REQUEST_LINE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequestStatus", b =>
                {
                    b.Property<long>("RequestStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestStatusId");

                    b.ToTable("INVENTORY_REQUEST_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequestType", b =>
                {
                    b.Property<long>("RequestTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RequestTypeId");

                    b.ToTable("INVENTORY_REQUEST_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Permission", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PERMISSION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Reservation", b =>
                {
                    b.Property<long>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReservationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReservationStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ReservedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ReservationNo")
                        .IsUnique();

                    b.HasIndex("ReservationStatusId");

                    b.HasIndex("ReservedByUserId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("RESERVATION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.ReservationLine", b =>
                {
                    b.Property<long>("ReservationLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QtyReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RequestLineId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestLineId");

                    b.HasIndex("ReservationId");

                    b.ToTable("RESERVATION_LINE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.ReservationStatus", b =>
                {
                    b.Property<long>("ReservationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReservationStatusId");

                    b.ToTable("RESERVATION_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GrantedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("ROLE_PERMISSION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.RolePermissionScope", b =>
                {
                    b.Property<long>("RolePermissionScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccessScopeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RolePermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RolePermissionScopeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RolePermissionId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ROLE_PERMISSION_SCOPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.SecurityEventType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("SECURITY_EVENT_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockLevel", b =>
                {
                    b.Property<long>("StockLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OnHandQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReservedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockLevelId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("STOCK_LEVEL");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockMovement", b =>
                {
                    b.Property<long>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MovementStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MovementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PostedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReasonCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReferenceRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReferenceReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReversedMovementId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockMovementId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MovementTypeId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("ReferenceRequestId");

                    b.HasIndex("ReferenceReservationId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("STOCK_MOVEMENT");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockMovementLine", b =>
                {
                    b.Property<long>("StockMovementLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineNotes")
                        .HasColumnType("TEXT");

                    b.Property<long>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QtyDeltaOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QtyDeltaReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<long>("StockMovementId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("StockMovementLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockMovementId");

                    b.ToTable("STOCK_MOVEMENT_LINE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("InvServer.Core.Entities.UserDepartment", b =>
                {
                    b.Property<long>("UserDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserDepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_DEPARTMENT");
                });

            modelBuilder.Entity("InvServer.Core.Entities.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("USER_ROLE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Warehouse", b =>
                {
                    b.Property<long>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WarehouseId");

                    b.ToTable("WAREHOUSE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowActionType", b =>
                {
                    b.Property<long>("WorkflowActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDecision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowActionTypeId");

                    b.ToTable("WORKFLOW_ACTION_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowAssignmentMode", b =>
                {
                    b.Property<long>("AssignmentModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentModeId");

                    b.ToTable("WORKFLOW_ASSIGNMENT_MODE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowConditionOperator", b =>
                {
                    b.Property<long>("WorkflowConditionOperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowConditionOperatorId");

                    b.ToTable("WORKFLOW_CONDITION_OPERATOR");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstance", b =>
                {
                    b.Property<long>("WorkflowInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessEntityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentWorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InitiatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkflowInstanceStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowInstanceId");

                    b.HasIndex("CurrentWorkflowStepId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("WorkflowInstanceStatusId");

                    b.HasIndex("WorkflowTemplateId");

                    b.ToTable("WORKFLOW_INSTANCE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstanceManualAssignment", b =>
                {
                    b.Property<long>("ManualAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManualAssignmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowStepId");

                    b.ToTable("WORKFLOW_INSTANCE_MANUAL_ASSIGNMENT");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstanceStatus", b =>
                {
                    b.Property<long>("WorkflowInstanceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowInstanceStatusId");

                    b.ToTable("WORKFLOW_INSTANCE_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStep", b =>
                {
                    b.Property<long>("WorkflowStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkflowStepTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowStepId");

                    b.HasIndex("WorkflowStepTypeId");

                    b.HasIndex("WorkflowTemplateId", "StepKey")
                        .IsUnique();

                    b.ToTable("WORKFLOW_STEP");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStepRule", b =>
                {
                    b.Property<long>("WorkflowStepRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDelegate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowReassign")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRequesterSelect")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssignmentModeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinApprovers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAll")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SLA_Minutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseRequesterDepartment")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowStepRuleId");

                    b.HasIndex("AssignmentModeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("WorkflowStepId")
                        .IsUnique();

                    b.ToTable("WORKFLOW_STEP_RULE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStepType", b =>
                {
                    b.Property<long>("WorkflowStepTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowStepTypeId");

                    b.ToTable("WORKFLOW_STEP_TYPE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTask", b =>
                {
                    b.Property<long>("WorkflowTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTaskStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowTaskId");

                    b.HasIndex("ClaimedByUserId");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowStepId");

                    b.HasIndex("WorkflowTaskStatusId");

                    b.ToTable("WORKFLOW_TASK");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskAction", b =>
                {
                    b.Property<long>("WorkflowTaskActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ActionByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorkflowActionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowTaskActionId");

                    b.HasIndex("ActionByUserId");

                    b.HasIndex("WorkflowActionTypeId");

                    b.HasIndex("WorkflowTaskId");

                    b.ToTable("WORKFLOW_TASK_ACTION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskAssignee", b =>
                {
                    b.Property<long>("WorkflowTaskAssigneeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("AssigneeStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowTaskAssigneeId");

                    b.HasIndex("AssigneeStatusId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowTaskId");

                    b.ToTable("WORKFLOW_TASK_ASSIGNEE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskAssigneeStatus", b =>
                {
                    b.Property<long>("AssigneeStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssigneeStatusId");

                    b.ToTable("WORKFLOW_TASK_ASSIGNEE_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskStatus", b =>
                {
                    b.Property<long>("WorkflowTaskStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowTaskStatusId");

                    b.ToTable("WORKFLOW_TASK_STATUS");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTemplate", b =>
                {
                    b.Property<long>("WorkflowTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("WorkflowTemplateId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SourceTemplateId");

                    b.ToTable("WORKFLOW_TEMPLATE");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTransition", b =>
                {
                    b.Property<long>("WorkflowTransitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FromWorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ToWorkflowStepId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowActionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WorkflowTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowTransitionId");

                    b.HasIndex("FromWorkflowStepId");

                    b.HasIndex("ToWorkflowStepId");

                    b.HasIndex("WorkflowActionTypeId");

                    b.HasIndex("WorkflowTemplateId", "FromWorkflowStepId", "WorkflowActionTypeId")
                        .IsUnique();

                    b.ToTable("WORKFLOW_TRANSITION");
                });

            modelBuilder.Entity("InvServer.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvServer.Core.Entities.AuthSession", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Category", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequest", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.InventoryRequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId");

                    b.HasOne("InvServer.Core.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId");

                    b.Navigation("Department");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Status");

                    b.Navigation("Warehouse");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequestLine", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.InventoryRequest", "Request")
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Product", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Reservation", b =>
                {
                    b.HasOne("InvServer.Core.Entities.InventoryRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("InvServer.Core.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany()
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "ReservedByUser")
                        .WithMany()
                        .HasForeignKey("ReservedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("ReservationStatus");

                    b.Navigation("ReservedByUser");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InvServer.Core.Entities.ReservationLine", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.InventoryRequestLine", "RequestLine")
                        .WithMany()
                        .HasForeignKey("RequestLineId");

                    b.HasOne("InvServer.Core.Entities.Reservation", "Reservation")
                        .WithMany("Lines")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RequestLine");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("InvServer.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InvServer.Core.Entities.RolePermissionScope", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("InvServer.Core.Entities.RolePermission", "RolePermission")
                        .WithMany("Scopes")
                        .HasForeignKey("RolePermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Department");

                    b.Navigation("RolePermission");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockLevel", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockMovement", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.InventoryMovementType", "MovementType")
                        .WithMany()
                        .HasForeignKey("MovementTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "PostedByUser")
                        .WithMany()
                        .HasForeignKey("PostedByUserId");

                    b.HasOne("InvServer.Core.Entities.InventoryRequest", "ReferenceRequest")
                        .WithMany()
                        .HasForeignKey("ReferenceRequestId");

                    b.HasOne("InvServer.Core.Entities.Reservation", "ReferenceReservation")
                        .WithMany()
                        .HasForeignKey("ReferenceReservationId");

                    b.HasOne("InvServer.Core.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("MovementType");

                    b.Navigation("PostedByUser");

                    b.Navigation("ReferenceRequest");

                    b.Navigation("ReferenceReservation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockMovementLine", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.StockMovement", "StockMovement")
                        .WithMany("Lines")
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockMovement");
                });

            modelBuilder.Entity("InvServer.Core.Entities.UserDepartment", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany("Departments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvServer.Core.Entities.UserRole", b =>
                {
                    b.HasOne("InvServer.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "CurrentStep")
                        .WithMany()
                        .HasForeignKey("CurrentWorkflowStepId");

                    b.HasOne("InvServer.Core.Entities.User", "InitiatorUser")
                        .WithMany()
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowInstanceStatus", "WorkflowInstanceStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany()
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentStep");

                    b.Navigation("InitiatorUser");

                    b.Navigation("WorkflowInstanceStatus");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstanceManualAssignment", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStep", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowStepType", "StepType")
                        .WithMany()
                        .HasForeignKey("WorkflowStepTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepType");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStepRule", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowAssignmentMode", "AssignmentMode")
                        .WithMany()
                        .HasForeignKey("AssignmentModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("InvServer.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "WorkflowStep")
                        .WithOne("Rule")
                        .HasForeignKey("InvServer.Core.Entities.WorkflowStepRule", "WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentMode");

                    b.Navigation("Department");

                    b.Navigation("Role");

                    b.Navigation("WorkflowStep");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTask", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("ClaimedByUserId");

                    b.HasOne("InvServer.Core.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "WorkflowStep")
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTaskStatus", "WorkflowTaskStatus")
                        .WithMany()
                        .HasForeignKey("WorkflowTaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaimedByUser");

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStep");

                    b.Navigation("WorkflowTaskStatus");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskAction", b =>
                {
                    b.HasOne("InvServer.Core.Entities.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("WorkflowActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTask", "WorkflowTask")
                        .WithMany("Actions")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("ActionType");

                    b.Navigation("WorkflowTask");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTaskAssignee", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowTaskAssigneeStatus", "AssigneeStatus")
                        .WithMany()
                        .HasForeignKey("AssigneeStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTask", "WorkflowTask")
                        .WithMany("Assignees")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssigneeStatus");

                    b.Navigation("User");

                    b.Navigation("WorkflowTask");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTemplate", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowTemplate", "SourceTemplate")
                        .WithMany()
                        .HasForeignKey("SourceTemplateId");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "FromStep")
                        .WithMany()
                        .HasForeignKey("FromWorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowStep", "ToStep")
                        .WithMany()
                        .HasForeignKey("ToWorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("WorkflowActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvServer.Core.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("FromStep");

                    b.Navigation("ToStep");

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("InvServer.Core.Entities.InventoryRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Reservation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvServer.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("InvServer.Core.Entities.RolePermission", b =>
                {
                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("InvServer.Core.Entities.StockMovement", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InvServer.Core.Entities.User", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowStep", b =>
                {
                    b.Navigation("Rule");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTask", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Assignees");
                });

            modelBuilder.Entity("InvServer.Core.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
